name: Run Pylint Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # use a known build environment
    container: python:3.8-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pylint
        run: pylint --load-plugins "pylint_flask_sqlalchemy, pylint_flask" service tests/test_routes.py tests/test_models.py run.py
